### ISSUE TITLE
Integrate proper tags for Google Analytics

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#107]
As on iOS, we want to track the following views with the following names:
- downloading view: "Downloading/[File name without extension]" (ex: Downloading/Wind_355)
- grid view: "Library/[File name of plist]" (ex: "Library/Magazines")
- ad view at startup: "Interstitial/[File name of ad] (ex: "Interstitial/Ad-drawable-large-land")
- pdf page view "PDFReader/[File name of pdf]/[Page number] (ex: "PDFReader/Wind_344/page3) 

Note: a pdf page view should be registered for each page displayed; if in landscape mode, register the 2 pages views.

**Comment by libreliodev** [comment]
@intrications I have question please. With the code changes, are we still tracking all downloads with `downloading view: "Downloading/[File name without extension]"`

**Comment by intrications** [comment]
@libreliodev 

It's in the code so it should be working.

https://github.com/libreliodev/android/blob/master/main/src/main/java/com/librelio/service/MagazineDownloadService.java#L126

**Comment by libreliodev** [comment]
@intrications 

Thanks, but this does not seem to track succeeded downloads. I think we should do it as on iOS: https://github.com/libreliodev/android/issues/292
