### ISSUE TITLE
The app crashes when I use my own libmupdf.so

### ISSUE THREAD

**Issue by bagusflyer** [libreliodev/android#208]
Hi, my app crashes when I use my own libmupdf.so. The error message is something like:" The native function doesn't exist in MuCore.openFile()". I guess it because I used my own libmupdf.so (I just compiled it by myself. The reason I compiled it is because I want to use x86 library. Anyway it crashes even when I'm using my own armeabi-v7a library.)

Did you compile your mupdf with some special flag? Thanks

**Comment by tejalpandya** [comment]
I m using mupdf library for pdf reader writer. but problem is that its not got highlighted text in lolipop version. so can u suggest which library is latest? Give me reply.

**Comment by intrications** [comment]
@tejalpandya 

I have no idea. The MuPDF java code was embedded in the app and altered so updating the MuPDF library is probably more complicated than just updating MuPDF.

There are open issues to update the MuPDF library used in the app and to make sure it works on all supported versions of Android.

#277 #281

**Comment by tejalpandya** [comment]
libmupdf.so file not highlight text in android 5.0 version. anybody will tell me how to use on higher version
