### ISSUE TITLE
Integrate sharing features as in our iOS app, and in our Test Matos Android apps

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#220]
The source code of this feature in our iOS apps is at https://github.com/libreliodev/iOS/blob/c8baf0c58513c1d33d4d131ebe2b187343119ce0/Classes/WAShareView.m

Basically, sharing should be triggered by a url under the following form
    
    share://[imageurl]?wasites=[sites]&waurl=[desturl]&watitle=[title]&watext=[text]

where:
- [imageurl] = url of image to display for sharing (without http://)
- [sites]=mail,facebook,twitter (or any combination of these)
- [desturl]= link to include in sharing
- [title]= title of sharing
- [text]= text of sharing

**Comment by lgdi** [comment]
No longer needed.
