### ISSUE TITLE
Make it possible to customize translations

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#243]
This should be done in a similar way as https://github.com/libreliodev/iOS/issues/72 .

**Comment by intrications** [comment]
This should now be easily possible with Gradle and product flavours.

**Comment by libreliodev** [comment]
@intrications Thanks a lot for your comment. My understanding is that product flavours in Gradle are similar to targets on iOS. If I am right, I am not sure it's a good option. We originally used different targets for different customers and apps on iOS, but it quickly became unmanageable. Having a different customization folder for each app, from where you get all specific elements (including specific translations) using a bash script, is a much better option according to me.

**Comment by intrications** [comment]
@libreliodev 

Don't worry. I understand your concern. That is not my plan.

I have now set up the code to have one extra "script" product flavour. The bash script will copy all the files into this product flavour folder just for the build. The customizations can remain in a folder on Dropbox. (The bash script already does copy the files, it just copies the files over the top of the main ones at the moment.)

But this "script" product flavour allows us to override all resources including strings, images and layouts and it will handle merging of the resources.

**Comment by libreliodev** [comment]
@intrications 

Sorry, I just wanted to make absolutely sure we understood each other!
This is absolutely brilliant, many thanks.

cc @ahazeb

**Comment by intrications** [comment]
@libreliodev 

No problem, I'm just glad the Android build tools have improved to the stage where this is possible. It's why I was so eager to switch to Gradle.
