### ISSUE TITLE
Implement html and csv viewers

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#260]
An html reader was added in the html branch (https://github.com/libreliodev/android/tree/html) a year ago. We want to make it work the way it does on iOS:
- the viewer can be opened from either a pdf or plist (or any other upcoming format, using links)
- viewer can use local files, either embedded in the app or downloaded from the server
- if a waupdate arg is added to the url (for example http://localhost/myfile.html?waupdate=30), the local file should be updated accordingly

Additionally, we are going to add a javascript based csv viewer (see https://github.com/libreliodev/javascript/issues/102 ) . This should work in a similar way as the html viewer; however, it will open a csvreader.html page that will be provided later, with a reference to the csv file, which will be loaded via ajax.

**Comment by lgdi** [comment]
No longer needed.
