### ISSUE TITLE
Improve crash reporting

### ISSUE THREAD

**Issue by intrications** [libreliodev/android#282]
Sending crash reports by email using ACRA is not as helpful as it could be.

1. Users have to manually send the crash report. They may not understand why a request to send an email has popped up and so we are probably missing lots of reports.

2. It is very difficult to tell if a crash is a one-off problem or a regular problem for many users.

I recommend either

a) setting up a [acralyzer](https://github.com/ACRA/acralyzer) server and continue to use ACRA.

b) using Crashlytics which is free.

Crashlytics is probably the best option.

Crash reports will be sent automatically in the background so we will get much better coverage of crashes. A privacy switch can be added to the app to turn this on and off - or the user could be asked when the first crash happens or on first run of the app.

**Comment by intrications** [comment]
Which option would you prefer? Crashlytics or acralyzer?

I'm not sure how easily Crashlytics would work with your custom bash script because it uses a Gradle plugin. But it would be the better option due to it being free and not having to run your own server.

**Comment by libreliodev** [comment]
@intrications 

> Which option would you prefer? Crashlytics or acralyzer?

Crashlytics
