### ISSUE TITLE
Splash Screen freezes with bad internet connection

### ISSUE THREAD

**Issue by intrications** [libreliodev/android#283]
For some reason the timeouts for the advertising request are not working:

https://github.com/libreliodev/android/blob/master/main/src/main/java/com/librelio/activity/StartupActivity.java#L92

(This only shows a read timeout, but I have tried with a connection timeout as well.)

The request should be timed and cancelled after 2 seconds. Here is some sample code.
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/CancelCall.java

Also, the activity should be advanced to the main activity after 2 seconds regardless of how long it took to download the advertising Plist.

**Comment by intrications** [comment]
@libreliodev Are there any current publications that currently have an advert on the splash screen that I can test with?

Also, there appears to be code to that goes to the main grid view rather than to view the advert link in a WebView if you click in a certain position on the advert (maybe the top 20%). Is this expected?

https://github.com/libreliodev/android/blob/master/main/src/main/java/com/librelio/activity/StartupActivity.java#L234

**Comment by libreliodev** [comment]
@intrications 

> Are there any current publications that currently have an advert on the splash screen that I can test with?

Wind probably does, but I am not sure.

> Also, there appears to be code to that goes to the main grid view rather than to view the advert link in a WebView if you click in a certain position on the advert (maybe the top 20%). Is this expected?

Yes.


Please note that we should be implementing DFP shortly, and in this case we will not need this code anymore. See #288

**Comment by intrications** [comment]
DFP now implemented so this should now be fixed.
