### ISSUE TITLE
Implement new covers view

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#285]
We need to implement a better looking covers view. 

There are 2 things we want to change:
* the most recent magazine should be more visible
- it should be possible to get more details about a magazine when tapping on cover.

A comp is available at http://librelio-europe.s3.amazonaws.com/developer/MaquetteBibliotheque.pdf

**Comment by intrications** [comment]
Where do the magazine details come from? Is that already in the plist or something?

What buttons will display if the user is already subscribed or if the user already owns the issue? Or none? I guess clicking on the magazine will just open it for reading.

**Comment by intrications** [comment]
Also, what about small screens like phones?

**Comment by libreliodev** [comment]
@intrications 

> Where do the magazine details come from? Is that already in the plist or something?

Text description will be added to the plist. Prices and subscription options will need to be retrieved from the Google Play server => I am not sure this will work smoothly enough.

> What buttons will display if the user is already subscribed or if the user already owns the issue? Or none? I guess clicking on the magazine will just open it for reading.

Yes.

> Also, what about small screens like phones?

A different comp will be provided later, but basically, in portrait mode, we should have the most recent magazine on the first line, and then 2 magazines per line.

**Comment by intrications** [comment]
> Text description will be added to the plist. Prices and subscription options will need to be retrieved from the Google Play server => I am not sure this will work smoothly enough.

I don't think it'll be too bad. Once the info is loaded once, it is cached. So it'll actually make the buy dialog appear quicker.

**Comment by intrications** [comment]
@libreliodev 

What is the row of magazines at the bottom? Is it a horizontally scrolling list? Or does the whole screen scroll up as a grid view (with the big header at the top)?

**Comment by libreliodev** [comment]
@intrications 

> What is the row of magazines at the bottom? Is it a horizontally scrolling list? Or does the whole screen scroll up as a grid view (with the big header at the top)?

 The whole screen scrolls up as a grid view (with the big header at the top).

**Comment by libreliodev** [comment]
@intrications 

> The mockup says "Subscribe for 3 months" on one of the buttons. Where does this come from? How does the app know whether there are monthly, 3 monthly or yearly subscriptions available?

`application_.xml` contains codes for monthly or yearly subscriptions. The app should query Google Play with these codes (if they exist), to check if the subscription is still available, and the price.

**Comment by libreliodev** [comment]
@intrications 

> Also, are username/password and subscriber code both still valid options?

Yes, both options are still valid.

**Comment by intrications** [comment]
> application_.xml contains codes for monthly or yearly subscriptions. The app should query Google Play with these codes (if they exist), to check if the subscription is still available, and the price.

So the 3 months was just an example. It should display whatever Google Play returns (which is in French for me for Wind) just as the BillingActivity currently does?

**Comment by libreliodev** [comment]
Yes

**Comment by intrications** [comment]
From https://github.com/libreliodev/iOS/issues/103#issuecomment-70616697:

> We should not forget to add a restore purchases option somewhere.

**Comment by libreliodev** [comment]
@intrications It would be nice if this could done in a similar way as on iOS, which almost completed now (see https://github.com/libreliodev/iOS/issues/103):
- Use 3 views: the grid view itself (with cell views), a header view possibly containing the first cover and/or an ad from DFP, and a modal giving more detail when user taps on a cover. 
- These 3 view should configurable using only xml
- If the header view contains the first cover (*), the grid view should obviously not display it again.

*: on iOS, we use xibs to customize the layouts. Each type of information (buttons, images, text) that can potentially be displayed has a numeric code. When we want the corresponding information to appear on the layout defined by the xib, we enter the numeric code as a tag for the element. For example, this header xib contains a cover (tag = 3).
![screenshot 2015-03-05 21 38 53](https://cloud.githubusercontent.com/assets/3107052/6514092/166013b0-c380-11e4-9511-7c47efa56897.png)

**Comment by libreliodev** [comment]
@intrications 

> Am I still meant to also be changing the layout to match the "MaquetteBibliotheque.key" that I started on earlier in the year?

This layout was intended to be a starting point for "design demanding" customers. 

> Is this meant to be the default layout for all the apps or should the previous layout also be kept?

Finally, we have decided to keep the previous layout. That's the way it's implemented on iOS. To implement specific layouts, we just need to change xibs. For example, the default header xib has height of 0, which simply means there is no header. 
If it's complicated now to implement on Android, please let me know.


cc @serverfire

**Comment by intrications** [comment]
@libreliodev 

We can customize it in almost the same way on Android by changing the layout xml files.

**Comment by libreliodev** [comment]
@intrications 

OK, great. I guess we will need to update the bash script we use to build the app?

**Comment by intrications** [comment]
@libreliodev 

There will be some smallish changes to the bash script.

**Comment by intrications** [comment]
Bash script updated. Layout can now be customized within the product folders within Dropbox. There are probably some tags from the iOS version not yet implemented.

**Comment by libreliodev** [comment]
@intrications

Can you please make sure that if no specific layout is provided in the "Dropbox" folder, the legacy layout is used?
