### ISSUE TITLE
Implement SDK for DoubleClick for Publishers (DFP)

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#288]
See https://developers.google.com/mobile-ads-sdk/

**Comment by libreliodev** [comment]
@intrications For testing, please use ad unit with code `/166877488/test`

**Comment by libreliodev** [comment]
@intrications DFP should also be used for startup interstitials instead of current system defined at https://github.com/libreliodev/android/issues/53

**Comment by intrications** [comment]
@libreliodev 

Should interstitials always be shown. Is there a setting to switch them on and off?

**Comment by libreliodev** [comment]
@intrications 

> Should interstitials always be shown. Is there a setting to switch them on and off?

On iOS, we have a setting

	<key>DfpPrefix</key>
	<string>/[LibrelioDFPid]/publisher_app_</string>

If this setting is defined, everything is managed via the DFP console (where it is possible to disable or pause interstitials). 

If this setting is not defined, we disable interstitials in the app.

**Comment by intrications** [comment]
@libreliodev So are there different codes for the interstitial and other ad units?

**Comment by libreliodev** [comment]
> So are there different codes for the interstitial and other ad units?

Yes.

- For startup interstitials, use `startup`. See https://github.com/libreliodev/iOS/blob/23ba4b25a1fe210d4aed256d42f76c7fa5abfffd/Classes/WAAppDelegate.m#L142
- For banners on covers view, use the name of the source plist (for example `Magazines`, `homme`, `femme`). See https://github.com/libreliodev/iOS/blob/23ba4b25a1fe210d4aed256d42f76c7fa5abfffd/Classes/WAPLIstParser.m#L235
- For banners in pdf, deduct name from link as usual, which should be under the form `ad://localhost/[code]`

**Comment by intrications** [comment]
@libreliodev This is implemented and works for interstitials and the current ad sizes.

If different ad sizes are required for custom layouts then that should be achievable just with custom dimension xml in the Dropbox folder.

**Comment by libreliodev** [comment]
Discussion to be continued in https://github.com/libreliodev/client-customizations/issues/12
