### ISSUE TITLE
Track succeeded downloads in a similar way as on iOS, using events

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#292]
This should be done as it's done on iOS here: https://github.com/libreliodev/iOS/blob/73526d49ac7d8e8942d3d74acd6d0303e1f60203/Classes/WADownloadingView.m#L285

**Comment by intrications** [comment]
Does the iOS app only track successful downloads? Not failures?

**Comment by libreliodev** [comment]
@intrications Thanks for your question. We actually realized  that tracking downloads with Google Analytics is not very reliable, so we are going to track them differently. More to come later.

**Comment by libreliodev** [comment]
We will finally keep tracking downloads using the same ethod as on iOS. We only track succeeded downloads for the time being.

**Comment by intrications** [comment]
This should now be sending the same as the iOS app. The only thing that might be different is the label.

**Comment by libreliodev** [comment]
Thanks. We'll correct it if needed.

cc @Ageleswari
