### ISSUE TITLE
Make it possible to add overlays only in a given orientation

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#296]
Similar to https://github.com/libreliodev/iOS/issues/119

cc @intrications

**Comment by intrications** [comment]
I'm not sure what "overlays" means. Does it mean things like the slideshows and videos?

**Comment by libreliodev** [comment]
@intrications 

> I'm not sure what "overlays" means. Does it mean things like the slideshows and videos?

Yes, that's the term used by Adobe, so we suggest using it now (instead of "enhancements" or "enrichments")

**Comment by intrications** [comment]
@libreliodev Is there an example to test this with?

**Comment by libreliodev** [comment]
@intrications 

> Is there an example to test this with?

Numero 162, page 2+3

**Comment by intrications** [comment]
Implemented but there may be out-of-memory issues #194

**Comment by libreliodev** [comment]
@intrications Indeed, there are out-of-memeory issues on an old Galaxy Tab. Can something be done?

**Comment by intrications** [comment]
I've tried switching to Picasso to load the images (which is a good idea anyway just for better code).

However, it doesn't seem to have improved the problem.

These are very large images we are displaying on top of the large images created to display the PDF. It is possible they are not being cleared out of memory correctly once they aren't on screen.

**Comment by libreliodev** [comment]
OK. I guess Crashlytics will tell us how critical the issue is.
