### ISSUE TITLE
When argument watoggle=no is added to url for slide show, prevent toggle full screen

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#297]
Similar to https://github.com/libreliodev/iOS/issues/128

cc @intrications

**Comment by intrications** [comment]
@libreliodev Is there an example to test this with?

**Comment by libreliodev** [comment]
@intrications 

> Is there an example to test this with?

Numero 162, page 2-3

**Comment by intrications** [comment]
@libreliodev I don't understand what this means.

Is this implemented in the iOS app? Double tapping on the images zooms them. Is that what you are trying to prevent?

Otherwise how is the fullscreen toggled?

**Comment by libreliodev** [comment]
@intrications 

> Is this implemented in the iOS app? 

Yes

> Double tapping on the images zooms them. Is that what you are trying to prevent?

Yes. 

In certain cases, we do not want the image to appear in full screen when tapped. For example, on page 2-3 of Numero 162, we have a double page spread in landscape orientation. We don't want half of it to appear in full screen when tapped.

**Comment by intrications** [comment]
Just to confirm, I have just compiled the latest version of the iOS code and run it on my iPad. Double tapping on page 2 to 3 of 162 zooms the image. This is what you say shouldn't happen.

Maybe I don't have the latest version of the code or I need to clean the build.

Anyway, I think I understand now so I can implement it now.

**Comment by intrications** [comment]
@libreliodev 

I think I understand now that the double tap zooming is just the app zooming in on the PDF with the overlay on top.

It is not becoming full screen so I think this is implemented.

**Comment by libreliodev** [comment]
@intrications  Successfully tested
