### ISSUE TITLE
Splashscreen image should have higher resolution

### ISSUE THREAD

**Issue by intrications** [libreliodev/android#298]
1280 x 720 images look pretty bad on high resolution Android tablet.

**Comment by libreliodev** [comment]
@intrications So, what resolution is needed please?

**Comment by intrications** [comment]
I'm testing on a Yoga 2 Pro with a resolution of 3200×1800.

But I think 1920x1080 is probably a good compromise and should look good.

**Comment by libreliodev** [comment]
@intrications 

> But I think 1920x1080 is probably a good compromise and should look good.

In which directory should it be put? https://github.com/libreliodev/android/wiki/Customization#preparing-the-assets-for-customization

**Comment by libreliodev** [comment]
@intrications 

Sorry to insist, can you let us know in which directories the new images should be put?

**Comment by intrications** [comment]
Sorry didn't see the message. 

Specifically the problem here would be the images for the xlarge bucket. But the best thing to do would be to put the images in the root of the Android folder in Dropbox and I will put them in the correct place.

**Comment by intrications** [comment]
@libreliodev 

Are the startup images (and list backgrounds) usually the same for small screens and large screens? Just different resolutions?

If so, then they can just go in drawable-nodpi and drawable-nodpi-land and let the system fit them to the screen. This will also help reduce the size of the app by no duplicating images.

**Comment by libreliodev** [comment]
No, unfortunately, we can not use the same images. Maybe we'll do so in the future.

**Comment by intrications** [comment]
This can be implemented on a case by case basis in the product folders in Dropbox. Fixed for current projects.
