### ISSUE TITLE
Sometimes, covers view remains blank for a long time

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#302]
Subissue of #285.

**Comment by intrications** [comment]
Which covers are these? The large ones or small ones?

The large ones are downloading the newsstand images so will be slower to download. I guess the slower ones may be delayed by these bigger downloads, although the app should cancel downloads if the covers are scrolled passed before the download finishes.

**Comment by intrications** [comment]
The pop up dialogs are always using the newsstand images because they display bigger. Maybe this isn't required on a phone sized device.

**Comment by libreliodev** [comment]
@intrications 

> Which covers are these? The large ones or small ones?

See screenshot below

> The large ones are downloading the newsstand images so will be slower to download. I guess the slower ones may be delayed by these bigger downloads, although the app should cancel downloads if the covers are scrolled passed before the download finishes.

Can't we display the covers view with generic covers while real covers are being downloaded? That's what we do on iOS.

> The pop up dialogs are always using the newsstand images because they display bigger. Maybe this isn't required on a phone sized device.

Maybe, but I don't think this specific point is urgent.



![2015-04-14 16 43 58](https://cloud.githubusercontent.com/assets/3107052/7139216/4cdbfa80-e2c5-11e4-9d86-3c1f674b2e9d.png)

**Comment by intrications** [comment]
@libreliodev 

Ah, sorry. Misunderstood. I thought you meant the actual cover images were downloading slowly and they were appearing blank until the image downloads. I realise the correct problem now.

This issue is very puzzling to me but trying to debug it now.

**Comment by intrications** [comment]
@libreliodev 

This is possibly fixed in the latest code. Haven't been able to test it enough yet but I did find a bug.

**Comment by libreliodev** [comment]
@intrications I have tested it, and noticed that there is no longer a blank screen when opening the covers view. However, when rotating the device, the blank screen appears and there does not seem to be a way to get out of it. Even when rotating back to the original orientation, the screen remains blank.

![2015-04-15 06 39 49](https://cloud.githubusercontent.com/assets/3107052/7152311/80be9316-e339-11e4-9119-e8ae7cf5b117.png)

**Comment by intrications** [comment]
Hopefully finally all fixed.

**Comment by libreliodev** [comment]
This does seem to be fixed
