### ISSUE TITLE
On certain devices, buttons on covers view are just black

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#303]
Subissue of #285 

![2015-04-13 17 05 57](https://cloud.githubusercontent.com/assets/3107052/7123078/dc279916-e21f-11e4-87ab-fb36c243bd15.png)

**Comment by intrications** [comment]
@libreliodev What version of Android is this on? I'm going to create an emulator to see if I can replicate

**Comment by libreliodev** [comment]
@intrications 

> What version of Android is this on? I'm going to create an emulator to see if I can replicate

4.1.2

**Comment by intrications** [comment]
Does anything change at all about them when you click them?

**Comment by libreliodev** [comment]
@intrications 

> Does anything change at all about them when you click them?

Here is what happens then:

![2015-04-14 15 45 36](https://cloud.githubusercontent.com/assets/3107052/7137849/c029987a-e2bc-11e4-9842-a88bef58fe37.png)

**Comment by intrications** [comment]
I mean does the black button change as you press on it. Does any part of it
change colour? For example, does the bordet turn grey?

**Comment by libreliodev** [comment]
@intrications 

> I mean does the black button change as you press on it. Does any part of it
change colour? For example, does the bordet turn grey?

It changes very slightly, but I can't define exactly what changes. Maybe the border is slightly different.

**Comment by intrications** [comment]
@libreliodev 

Reproduced in emulator and fixed in files in Dropbox.

**Comment by libreliodev** [comment]
Successfully tested
