### ISSUE TITLE
Cannot run project on simulator on Mac

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#305]
@intrications This may be because of my lack of knowledge concerning Android Studio but I can't run the project on the emulator.
I get an error message
```
Device is ready: 1GB_API_22 [emulator-5554]
Target device: 1GB_API_22 [emulator-5554]
Uploading file
	local path: []/android/main/build/outputs/apk/main-magazines-magazine-debug.apk
	remote path: /data/local/tmp/com.niveales.wind
Installing com.niveales.wind
DEVICE SHELL COMMAND: pm install -r "/data/local/tmp/com.niveales.wind"
pkg: /data/local/tmp/com.niveales.wind
Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
```

This may be related to #267. 

Also, I may be confused: is there a way to launch the app using the specific settings in Dropbox, without running the batch script before?

**Comment by intrications** [comment]
It is because of #267. The app doesn't include x86 libraries.

However I can't work out how to compile the newer versions properly. Lollipop had a breaking change which means native libraries built for it won't work on Android 4.0. And so it doesn't seem simple to build native libraries that work on pre 4.1 and 5.0+. However, the current (old) libraries do work for some reason.

This is mentioned in #281.

> is there a way to launch the app using the specific settings in Dropbox, without running the batch script before?

You can just copy the files from Dropbox to the main/src/script folder in the source folder. However it still needs to be compiled. Either on the command line or in Android Studio. The script does much less now - basically just copies the required files and signs the APK.

**Comment by libreliodev** [comment]
@intrications 

Thanks for the answers. Does it mean it's not possible to run the emulator on iOS? Can you suggest alternative option?

**Comment by intrications** [comment]
@libreliodev 

I'm not sure. It may involve having to change the minSDK to 16 (Android 4.1) or create separate APKs for Android 4.0.

One of the things that make it hard to update MuPDF is that MuPDF is not a library on Android. It is a sample app which includes and demonstrates usage of the PDF library.

So when our app was first written these files were just copied over and the git history doesn't show the changes that have been made clearly.

These are the files: https://github.com/libreliodev/android/tree/master/main/src/main/java/com/artifex/mupdfdemo

You can tell by the fact "demo" is in the package name that the files aren't from a library and possibly shouldn't been used in this way.

So when the new library is compile, sometimes the Java classes included in the app don't match up and cause hard to debug native crashes.

So it may be required to reintegrate MuPDF from scratch, hopefully keeping the changes clearer. I think some of the changes were made to do things like display two pages side by side in landscape.

**Comment by libreliodev** [comment]
@intrications 

Thanks for the explanation regarding MuPdf. I guess we need to address this issue quickly.

Regarding the emulator, do you have suggestions? Should we use PCs instead of Macs?!

**Comment by intrications** [comment]
@libreliodev 

Just realised, you need to use an ARM based emulator image. It's slower but will work. Windows and Mac will both have the same problem. Let me know if you need more information on how to do this.

I tried compiling MuPDF 1.7. Copied the compiled library files and just get a blank page when trying to view a PDF with "Render failed" in the logcat which seems to come from the native code.

**Comment by intrications** [comment]
Note that the app still works, for example, on my x86 based Lenovo tablet. It contains software from Intel which converts the ARM code to x86 as it runs.

This is mainly a problem for x86 emulators (and MIPS devices but I don't think there are many of them).

**Comment by intrications** [comment]
Issue tracked in #267
