### ISSUE TITLE
Preview download always fails after having been interrupted

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#307]
Steps to reproduce:

- tap on Preview
- download starts and button becomes "En attente" (in French version) and then displays % downlaod
- tap on button displaying % download
- button becomes "Download failed", and there is no way to start it again.

cc @intrications

**Comment by intrications** [comment]
Fixed with d9ab83d405053739a1bf75c307df48ee826dc5e8

**Comment by libreliodev** [comment]
Successfully tested
