### ISSUE TITLE
Wind App for android could not compile.

### ISSUE THREAD

**Issue by choimingyu** [libreliodev/android#310]
Hi.

I was deeply impressed from your app. 

I downloaded wind for android from GitHub.

but it can't compile.

Error message is 'Could not find com.afollestad:material-dialogs:0.7.2.3'.

I use Android Studio(v 1.2.1.1)

 

Please let me know how to solve this problem.

Thank you.

**Comment by intrications** [comment]
@choimingyu Please try compiling the latest code.
