### ISSUE TITLE
Errors Resolving Dependencies

### ISSUE THREAD

**Issue by cvsakpal** [libreliodev/android#312]
Hi,

I was trying to build the Android App. I get some errors while resolving dependencies for configuring ':appiraterAndroid:_debugCompile'. 
![appirater-bug](https://cloud.githubusercontent.com/assets/7136093/8802674/9ba163cc-2fe0-11e5-940c-3d7165f04d30.png)

I tried commenting out the dependency but I got another error while configuring the Main project.
![main-project-bug](https://cloud.githubusercontent.com/assets/7136093/8802689/b42e3c08-2fe0-11e5-914e-6bea349695d6.png)

Am I doing something wrong? Could someone please help me resolve these errors?
Thanks.

**Comment by libreliodev** [comment]
@cvsakpal Try updating everything in the Android SDK Manager 

cc @intrications

**Comment by cvsakpal** [comment]
@libreliodev Thanks, the "Android Support Repository" wasn't installed in the Android SDK. Its installation solved the 1st bug.
I'll check out what else is missing for the 2nd one...
I'll close the topic as soon as I figure this out...

**Comment by intrications** [comment]
@cvsakpal 

For some reason you aren't able to download the "gradle-versions-plugin" dependency from jcenter. It isn't essential to building the app so try setting the version to "0.11.1" in build.gradle to download it from Maven Central.

**Comment by cvsakpal** [comment]
Some time back I had installed SDK platform 19 for Android 4.2.2 cordova apps... Because of which I was getting the 2nd bug...
I also had to create the custom.gradle under /main/src/script (just mentioned it coz its not in the wiki), had no idea what to add to the custom.gradle file so duplicated the contents of build.gradle, edited applicationIDs, etc and removed the "Script" block from the custom.gradle on line 75 (since it was stuck in infinite loop)
Also I did not have the Google Play Services and other related Play related packages installed which created issues similar to the previously stated ones...
I just got the BUILD SUCCESSFUL message...

@intrications Thanks for your reply... Its working now... Some time tomorrow I'll check what I get with changing the version...
