### ISSUE TITLE
Implement MuPDF openBuffer

### ISSUE THREAD

**Issue by muotaz** [libreliodev/android#313]
Hello there, 

I am trying to implement MuPDF openBuffer method, but I can't find the SO version in use in the project.
So, which MuPDF is being used in Librelio?

**Comment by libreliodev** [comment]
@intrications Which version are we currently using please?

**Comment by intrications** [comment]
I think 1.5 plus a few commits later that fixed a bug on Android:

http://git.ghostscript.com/?p=mupdf.git;a=commit;h=38402bcf8dfea7b08cb5b3e6948af078d0b3874b

Here's the commit:
https://github.com/libreliodev/android/commit/71b5af62e9a2ba7f3e25a5e528d6465fcf8fe801

**Comment by muotaz** [comment]
I see, so in that case the openBuffer method exhibits the issue explained here:

http://stackoverflow.com/questions/22558597/mupdf-how-to-open-pdf-file-with-openbuffer-method

So I had to use the 1.7 precompiled binary from MuPDF site, but then I was faced with this issue:

http://stackoverflow.com/questions/32136233/mupdf-cannot-recognize-version-marker

Any idea on how to get openBuffer working ? Thanks in advance

**Comment by intrications** [comment]
@muotaz I don't know I'm afraid. There are multiple open issues on this project about how to update MuPDF as you can see here: https://github.com/libreliodev/android/issues/208#issuecomment-132504831. I've tried updating it but I keep getting problems.

**Comment by muotaz** [comment]
@intrications I think I was able to do it! I used the pre-compiled binary as I told you and then added some native library method declarations, added the cookie class, and modified drawPage method signature to conform to the new version (I have compared the sample MuPDF app and and went through the C code). And the openBuffer is working now.
