### ISSUE TITLE
Cannot find the code for pdf to image conversion

### ISSUE THREAD

**Issue by saipavan1223** [libreliodev/android#317]
Where is the code for converting pdf to images please help.

http://stackoverflow.com/questions/15358461/create-image-of-all-pages-in-pdf-using-mupdf-library

**Comment by avittecoqDAJ** [comment]
Hello,

After some searching I found in the class MuPDFCore a method called drawPage. I think that's what you are looking for.

I hope this helps.

**Comment by saipavan1223** [comment]
Hi Antonie,

          Thank you for your response I really appreciate it. I know about
the drawPage method.That is used to draw the bitmaps.But I want to draw
images.


Thank you,

**Comment by avittecoqDAJ** [comment]
Hello @saipavan1223,

A bitmap is a way to represents an image. You can save the bitmap as an image file using the android.graphics.bitmap.compress method. The documentation can be found here:
http://developer.android.com/reference/android/graphics/Bitmap.html#compress(android.graphics.Bitmap.CompressFormat, int, java.io.OutputStream).

I hope this helps.

**Comment by saipavan1223** [comment]
thank you for your help. I will take a look into it.Happy new year
