### ISSUE TITLE
Outdated code

### ISSUE THREAD

**Issue by sfilatovs** [libreliodev/android#318]
Hi, 

I've ran into multiple instances where app doesn't build or crashes due to the fact that code needs to be updated (starting with "target SDK", going to the "afollestad.material-dialogs:core:" being out of date and numerous other issues). 
I was wondering if you plan to update the code (I could make a more elaborate list of problems and some solutions I've found). 
Perhaps in the case you're not going to update, you could recommend another similar app that could be used.

Best,
Stas

**Comment by avittecoqDAJ** [comment]
Hello Stas,

The update of the application is planned. If you want to help us out, feel free to contribute.

Best,

Antoine

**Comment by sfilatovs** [comment]
Great, I am not a coder at all, so I've been just googling errors I was getting when trying to get the code running and then rewriting some parts as suggested on Stack Exchange. I will post here a list with the changes I've made to get the code running (but haven't been able to simulate yet).

**Comment by sfilatovs** [comment]
So, here is the list of the changes i've made so far to get the code working. 
Note, I don't know if it's possible to make the code running with less changes, most likely yes. 
I've been changing three files: 
main\build.gradle
appiraterAndroid\build.gradle
main\src\script\custom.gradle
Those are different build gradles. 
I am attaching the actual files (i've changed their names or convenience). 

I've modified main\build.gradle in the following way: 
changed version of sdk and other parameters to 23, explicitly indicated dependencies for appcompatv7 and others.
custom.gradle: i've copied the contents of the updated main/build.gradle into it as indicated [here](https://github.com/libreliodev/android/issues/312) commenting out the "custom.gradle" part.
appiraterAndroid/build.gradle: included newer version of afollestad and a repository for it as indicated [here](https://github.com/afollestad/material-dialogs#gradle-dependency) 

see the attached files, they contain all the changes (they're in txt format though, so if you want to change your code you need to copy-paste the code, not replace the files)

[appiraterAndroid-build.txt](https://github.com/libreliodev/android/files/168988/appiraterAndroid-build.txt)
[main-build.txt](https://github.com/libreliodev/android/files/168986/main-build.txt)
[main-src-script-custom.txt](https://github.com/libreliodev/android/files/168987/main-src-script-custom.txt)


.

**Comment by zh-wowtv** [comment]
I also want to contribute. But I'm using Android Studio. Is that OK?

**Comment by avittecoqDAJ** [comment]
Hello,

Yes it's okay.

**Comment by avittecoqDAJ** [comment]
Fixed by adae10ae3c4a621a72891c02b2ba62b47d572efc
