### ISSUE TITLE
how to use our  own servers

### ISSUE THREAD

**Issue by ilayangudi** [libreliodev/android#321]
I have my own hosting. Where should I upload my pdfs and what need to be changed in the app. Your help is appreciated.

**Comment by ilayangudi** [comment]
@sfilatovs any help is much appreciated

**Comment by sfilatovs** [comment]
Hey, I did not manage to upload my PDFs in the end. I can't even estimate
how much new code needs to be added.

**Comment by ilayangudi** [comment]
@sfilatovs  Noted. Thanks for the reply.

**Comment by avittecoqDAJ** [comment]
The app is designed to be used with Amazon S3 hosting service.
You could use your own Amazon S3 account, but it would require a lot of change if you want to use some different kind of storage services.
