### ISSUE TITLE
Upload my magazines to Librelio S3 server

### ISSUE THREAD

**Issue by ebongfrank** [libreliodev/android#324]
Hello, I have paid the for the Librelio developer plan and Uploaded my magazines. Upon customizing the APP, I am unable to see the uploaded magazines in my compiled APP.

Best Regards

Frank

**Comment by avittecoqDAJ** [comment]
Hello Frank,
What did you put in your customer.gradle file ?

**Comment by ebongfrank** [comment]
com.kamerun.emedia
