### ISSUE TITLE
How to improve PDF Reader Performance

### ISSUE THREAD

**Issue by shahalRahman** [libreliodev/android#328]
I am trying to intergate MuPDF Reader in my application. My PDF is high in graphics so it takes time to load i.e. around 4-5 second per page or some times little less.

1. We have to improve this loading experience somehow either by loading low resolution of PDF page first and then loading proper page on settle. Right now when you swipe, it shows loading and then after 4-5 second, it loads page.  Can we control this behavior ?

2. Also how we can improve loading of previous and next page? Is there any reference class we should check?

**Comment by avittecoqDAJ** [comment]
This is Librelio's magazine reader repository's issues space. If you are working with Librelio Application, then MuPDF is already integrated in the application.
If you have question about MuPDF, then you should ask the MuPDF community and it's not here. You can also try StackOverflow.
In our case, we recommend to use only low definition PDF so it loads faster, so we don't have the problem you encounter.
